# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json
PackageIdentifier: DerellLicht.WBigCalc
PackageVersion: 6.12
PackageLocale: en-US
Publisher: Derell Licht
PublisherUrl: https://github.com/DerellLicht
PackageUrl: https://github.com/DerellLicht/wbigcalc
PackageName: WBigCalc
Moniker: wbigcalc
License: CC0-1.0
LicenseUrl: https://github.com/DerellLicht/wbigcalc/blob/main/LICENSE.txt
ReleaseNotesUrl: https://github.com/DerellLicht/wbigcalc/releases/tag/v6.12
ShortDescription: WBigCalc is an extended-precision RPN (Reverse Polish Notation) scientific calculator.
Description: |-
  WBigCalc is an extended-precision scientific calculator, supporting numbers up to 1075 digits.
  WBigCalc uses Reverse Polish Notation (RPN), as originally used in HP calculators;
  RPN is an efficient method for handling complex computations, but is rarely seen in pocket calculators any more.
Tags:
- extended-precision
- scientific-calculator
- calculator
- rpn
ManifestType: defaultLocale
ManifestVersion: 1.12.0
